config/routes.rb
MinibankApp::Application.routes.draw do
  resources :posts

  root to: 'sessions#new'

  resources :sessions
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"

  resources :clients do
    resources :accounts
  end

  resources :accounts do
    resources :transactions
  end
end

app/models/account.rb
# encoding: utf-8
class Account < ActiveRecord::Base
  belongs_to :client
  has_many :transactions, dependent: :destroy

  validates :balance, numericality: { only_integer: true }

  before_create :set_number

  def to_s
    "[#{number}] #{balance} zł"
  end

  def update_balance!
    sum = transactions.map { |t| t.amount }.sum
    update_attribute(:balance, sum)
  end

  protected
    def set_number
      self.number = rand 1_000_000_000
    end
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :accounts, dependent: :destroy

  has_secure_password

  validates :name, :surname, length: { minimum: 2 }
  validates :email, format: { with: /\A.+@.+\z/ }
  validates :phone, format: { with: /\A\d{3}-\d{3}-\d{3}\z/ }

  def to_s
    "#{name} #{surname} (#{id})"
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :account

  after_save :update_account_balance

  validates :descr, presence: true
  validates :amount, numericality: { only_integer: true }

  protected
    def update_account_balance
      account.update_balance!
    end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :find_client
  before_filter :find_account, only: [:show, :destroy]

  def index
    @accounts = @client.accounts.order('id').page(params[:page])
  end

  def show
  end

  def create
    @account = @client.accounts.create!
    redirect_to client_accounts_path(@client)
  end

  def destroy
    @account.destroy
    redirect_to client_accounts_path(@client)
  end

  private
    def find_client
      @client = current_client
    end

    def find_account
      @account = @client.accounts.find(params[:id])
    end
end

app/controllers/application_controller.rb
# encoding: utf-8
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_client!

  protected
    def current_client
      @current_client ||= Client.find(session[:client_id]) if session[:client_id]
    end
    helper_method :current_client

    def authenticate_client!
      if current_client.nil?
        redirect_to login_path, alert: 'Proszę się zalogować.'
      end
    end
end

app/controllers/clients_controller.rb
# encoding: utf-8
class ClientsController < ApplicationController
  before_action :disabled, except: [:new, :create]
  skip_before_action :authenticate_client!, only: [:new, :create]
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  def index
    @clients = Client.all.page(params[:page])
  end

  # GET /clients/1
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  def create
    @client = Client.new(client_params)

    if @client.save
      ClientMailer.welcome(@client).deliver
      redirect_to login_path, notice: 'Client was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /clients/1
  def update
    if @client.update(client_params)
      redirect_to @client, notice: 'Client was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /clients/1
  def destroy
    @client.destroy
    redirect_to clients_url, notice: 'Client was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :surname, :email, :phone,
                                     :password, :password_confirmation)
    end

    def disabled
      raise 'Disabled!!!'
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authenticate_client!

  caches_page :index, :show

  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
      expire_index
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
      expire_page action: 'show', id: params[:id]
      expire_index
    else
      render action: 'edit'
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    expire_index
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end

    def expire_index
      expire_page action: 'index'
    end
end

app/controllers/sessions_controller.rb
# encoding: utf-8
class SessionsController < ApplicationController
  skip_before_filter :authenticate_client!, except: [:destroy]

  def new
  end

  def create
    client = Client.find_by_email(params[:email])
    if client && client.authenticate(params[:password])
      session[:client_id] = client.id
      redirect_to client_accounts_path(client), notice: 'Witamy :)'
    else
      flash.now.alert = 'Błędny email i/lub hasło :('
      render action: 'new'
    end
  end

  def destroy
    session[:client_id] = nil
    redirect_to root_path, notice: 'Do zobaczenia...'
  end
end

app/controllers/transactions_controller.rb
# encoding: utf-8
class TransactionsController < ApplicationController
  before_filter :find_account

  def index
    @transactions = @account.transactions.order('id desc').page(params[:page])
  end

  def new
    @transaction = @account.transactions.new
  end

  def create
    @transaction = @account.transactions.new(transaction_params)
    if @transaction.save
      redirect_to [@client, @account], notice: 'Transakcja zapisana'
    else
      render action: 'new'
    end
  end

  private
    def find_account
      @client = current_client
      @account = @client.accounts.find(params[:account_id])
    end

    def transaction_params
      params.require(:transaction).permit(:amount, :descr)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
# encoding: utf-8
module ApplicationHelper
  def money(amount, currency='zł')
    "#{amount} #{currency}"
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/accounts/_account.html.haml
%tr
  %td= account.number
  %td= money(account.balance)
  %td= link_to 'Show', [@client, account]
  %td= link_to 'Destroy', [@client, account], :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/accounts/index.html.haml
= content_for :client, @client

%h1 Konta klienta

%table.table
  %tr
    %th Numer
    %th Saldo
    %th
    %th

  = render @accounts

%p=paginate @accounts

%br

= link_to 'Nowe konto', client_accounts_path(@client), class: 'btn', method: :post

app/views/accounts/show.html.haml
= content_for :client, @client

%h1= @account

%p= link_to 'Lista transakcji', account_transactions_path(@account), class: 'btn'

app/views/clients/_form.html.haml
= form_for @client do |f|
  - if @client.errors.any?
    #error_explanation
      %h2= "#{pluralize(@client.errors.count, "error")} prohibited this client from being saved:"
      %ul
        - @client.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :surname
    = f.text_field :surname
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  .field
    = f.label :phone
    = f.text_field :phone
  .actions
    = f.submit 'Save'

app/views/clients/edit.html.haml
= content_for :client, @client

%h1 Editing client

= render 'form'

= link_to 'Show', @client
\|
= link_to 'Back', clients_path

app/views/clients/index.html.haml
%h1 Listing clients

%table.table
  %tr
    %th Name
    %th Surname
    %th Email
    %th Phone
    %th
    %th
    %th

  - @clients.each do |client|
    %tr
      %td= client.name
      %td= client.surname
      %td= client.email
      %td= client.phone
      %td= link_to 'Show', client
      %td= link_to 'Edit', edit_client_path(client)
      %td= link_to 'Destroy', client, :method => :delete, :data => { :confirm => 'Are you sure?' }

%p= paginate @clients

%br

= link_to 'New Client', new_client_path, class: 'btn'

app/views/clients/new.html.haml
%h1 New client

= render 'form'

= link_to 'Back', clients_path

app/views/clients/show.html.haml
= content_for :client, @client

%p
  %b Name:
  = @client.name
%p
  %b Surname:
  = @client.surname
%p
  %b Email:
  = @client.email
%p
  %b Phone:
  = @client.phone

= link_to 'Edit', edit_client_path(@client)
\|
= link_to 'Back', clients_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MinibankApp</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <style>
    body {
      padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
    }
  </style>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="brand" href="/">MinibankApp</a>
        <a class="brand" href="#"><%= yield :client %></a>
        <div class="nav-collapse collapse">
          <% if current_client %>
            <ul class="nav">
              <li><%= link_to 'Konta', client_accounts_path(@client) %></li>
              <li><%= link_to 'Wyloguj', logout_path %></li>
            </ul>
          <% end %>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>

  <div class="container">
    <% if notice.present? %><p class="alert alert-success"><%= notice %></p><% end %>
    <% if alert.present? %><p class="alert alert-error"><%= alert %></p><% end %>

    <%= yield %>
  </div>

</body>
</html>

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .actions
    = f.submit 'Save'

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%h1 Listing posts

%table
  %tr
    %th Title
    %th Body
    %th
    %th
    %th

  - @posts.each do |post|
    %tr
      %td= post.title
      %td= post.body
      %td= link_to 'Show', post
      %td= link_to 'Edit', edit_post_path(post)
      %td= link_to 'Destroy', post, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @post.title
%p
  %b Body:
  = @post.body

= link_to 'Edit', edit_post_path(@post)
\|
= link_to 'Back', posts_path

app/views/transactions/index.html.haml
%h2 Lista transakcji
%table.table
  %tr
    %th Data
    %th Kwota
    %th Opis
  - @transactions.each do |transaction|
    %tr
      %td= I18n.l transaction.created_at
      %td= money(transaction.amount)
      %td= transaction.descr

%p= paginate @transactions

%p= link_to 'Nowa transakcja', new_account_transaction_path(@account), class: 'btn'

app/views/transactions/new.html.haml
= content_for :client, @client

%h1 Nowa transakcja
%h2= @account

= form_for [@account, @transaction] do |f|
  - if @transaction.errors.any?
    #error_explanation
      %h2= "#{pluralize(@transaction.errors.count, "error")} prohibited this transaction from being saved:"
      %ul
        - @transaction.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :amount
    = f.text_field :amount
  .field
    = f.label :descr
    = f.text_field :descr
  .actions
    = f.submit 'Zapisz'